version = 1

test_patterns = [
  "**/*.test.ts",
  "**/*.test.tsx",
  "tests/**",
]

exclude_patterns = [
  "public/OneSignalSDK*.js",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs", "browser"]
  plugins = ["react"]
